# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Levi's Blog
subtitle: august's slipped away
author: Levi Liang
language: 
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://ashmorelevi.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

#Custom Setting Start

# Site settings
SEOTitle: Levi的博客 | Levi's Blog
header-img: /img/home-bg.png
email: 1069696543@qq.com
description: description test
keyword: keyword test
signature: false #show signature
signature-img: /img/signature/white.png 

# 自动生成sitemap
sitemap:
    path: sitemap.xml
baidusitemap:
    path: baidusitemap.xml
search:
    path: search.xml
    field: post
    format: html
    limit: 10000

# SNS settings
# RSS: false
zhihu_username:     
github_username:    
jianshu_username:

# Build settings
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

daovoice:
    enable: false
    app_id: ""
    email: ""

# Disqus settings

disqus:
    enable: false
    shortname: ""

# Duoshuo settings
duoshuo_share: false                     # set to false if you want to use Comment without Sharing

# Gitalk
gitalk:
  enable: false    #是否开启Gitalk评论
  clientID: 7bd18cd14435f89a4dfb                            #生成的clientID
  clientSecret: 87b3c3f9d0aa37f71d64aac84331b2e5e769b3a1    #生成的clientSecret
  repo: csjiabin.github.io    #仓库名称
  owner: csjiabin    #github用户名
  admin: csjiabin
  distractionFreeMode: true #是否启用类似FB的阴影遮罩

# Analytics settings
# Baidu Analytics
ba_track_id: 2620e69674d25088f870bef114e8ff89
bd_site_verification: aifbHeRmzy

# Google Analytics
ga_track_id: 'UA-124238838-1'            # Format: UA-xxxxxx-xx
ga_domain: csjiabin.github.io
google_site_verification: Xk9YWz2-rBE9P5__qdWz3nUr4zb9bIDSdANHpezjB04


# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "it'll pass"
sidebar-avatar: /img/head.jpg
#sidebar-avatar: https://avatars1.githubusercontent.com/u/20592953?s=460&v=4       # use absolute URL, seeing it's used in both `/` and `/about/`


# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# Friends
friends: [
    {
        title: "Latex",
        href: "https://www.latexlive.com/home"
    }
]

#Custom Setting End


# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: i_dont_wanna_use_default_archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: 
    - README.md
    - sw.js

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
# external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Markdown-it config
## Docs: https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki
markdown_it_plus:
    highlight: true
    html: true
    xhtmlOut: true
    breaks: true
    langPrefix:
    linkify: true
    typographer:
    quotes: “”‘’
    pre_class: highlight
    
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: huxblog

# MathJax Support
# mathjax:
# enable: true
# per_page: true

# Math Formulas Render Support
math:
  enable: true
  # Default (true) will load mathjax / katex script on demand.
  # That is it only render those page which has `mathjax: true` in Front-matter.
  # If you set it to false, it will load mathjax / katex srcipt EVERY PAGE.
  per_page: true
  engine: mathjax

  # hexo-renderer-pandoc (or hexo-renderer-kramed) required for full MathJax support.
  mathjax:
    enable: true
    # See: https://mhchem.github.io/MathJax-mhchem/
    mhchem: false

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/AshmoreLevi/AshmoreLevi.github.io.git
  branch: main


